[package]
name = "nds-emulator"
version = "0.1.0"
authors = ["Akash Munagala <akash.munagala@gmail.com>"]
edition = "2018"

[workspace]
members = ["core"]

[dependencies]
nds-core = { path = "core" }
